%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-pr2-camera-synchronizer
Version:        1.6.32
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pr2_camera_synchronizer package

License:        BSD
URL:            http://pr.willowgarage.com/wiki/pr2_camera_synchronizer
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-diagnostic-msgs
Requires:       ros-noetic-dynamic-reconfigure
Requires:       ros-noetic-ethercat-trigger-controllers
Requires:       ros-noetic-rospy
Requires:       ros-noetic-wge100-camera
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-dynamic-reconfigure
BuildRequires:  ros-noetic-rostest
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The PR2 is equipped with a texture projector that can be used to project a
texture onto featureless surfaces, allowing their three-dimensional structure to
be determined using stereoscopy. The projector operates in a pulsed mode,
producing brief (2ms) pulses of light. Cameras that want to see the texture must
expose during the projector pulse; other cameras should be expose while the
projector is off. This package contains the pr2_projector_synchronizer node.
Based on its dynamically reconfigurable parameters, this node controls the
projector pulsing, and sets up triggering of the WGE100 cameras.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed May 26 2021 Dave Feil-Seifer <dave@cse.unr.edu> - 1.6.32-1
- Autogenerated by Bloom

