Name:           ros-indigo-pr2-camera-synchronizer
Version:        1.6.10
Release:        4%{?dist}
Summary:        ROS pr2_camera_synchronizer package

Group:          Development/Libraries
License:        BSD
URL:            http://pr.willowgarage.com/wiki/pr2_camera_synchronizer
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-diagnostic-msgs
Requires:       ros-indigo-dynamic-reconfigure
Requires:       ros-indigo-ethercat-trigger-controllers
Requires:       ros-indigo-rospy
Requires:       ros-indigo-wge100-camera
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-dynamic-reconfigure
BuildRequires:  ros-indigo-rostest

%description
The PR2 is equipped with a texture projector that can be used to project a
texture onto featureless surfaces, allowing their three-dimensional structure to
be determined using stereoscopy. The projector operates in a pulsed mode,
producing brief (2ms) pulses of light. Cameras that want to see the texture must
expose during the projector pulse; other cameras should be expose while the
projector is off. This package contains the pr2_projector_synchronizer node.
Based on its dynamically reconfigurable parameters, this node controls the
projector pulsing, and sets up triggering of the WGE100 cameras.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Feb 22 2016 Devon Ash <ahendrix@willowgarage.com> - 1.6.10-4
- Autogenerated by Bloom

* Fri Jan 22 2016 Devon Ash <ahendrix@willowgarage.com> - 1.6.10-3
- Autogenerated by Bloom

* Fri Jan 08 2016 Devon Ash <ahendrix@willowgarage.com> - 1.6.10-2
- Autogenerated by Bloom

* Fri Dec 04 2015 Devon Ash <ahendrix@willowgarage.com> - 1.6.10-1
- Autogenerated by Bloom

* Wed Sep 16 2015 Devon Ash <ahendrix@willowgarage.com> - 1.6.10-0
- Autogenerated by Bloom

* Tue Sep 01 2015 Austin Hendrix <ahendrix@willowgarage.com> - 1.6.9-0
- Autogenerated by Bloom

* Fri Feb 13 2015 Austin Hendrix <ahendrix@willowgarage.com> - 1.6.7-0
- Autogenerated by Bloom

