Name:           ros-kinetic-pr2-run-stop-auto-restart
Version:        1.6.28
Release:        0%{?dist}
Summary:        ROS pr2_run_stop_auto_restart package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_run_stop_auto_restart
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-pr2-msgs
Requires:       ros-kinetic-pr2-power-board
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-std-srvs
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-pr2-msgs
BuildRequires:  ros-kinetic-pr2-power-board
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-std-srvs

%description
This package provides a node that monitors the state of the run stops of the
pr2_robot. When the state of the run stop changes from off to on, this node will
automatically enable the power to the motors, and reset the motors. This allows
you to use the run stop as a 'pause' button. By using the run stop as a tool to
power up the robot, the run stop is also in reach of the user once the robot
starts moving.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sat Apr 21 2018 Dave Feil-Seifer <dave@cse.unr.edu> - 1.6.28-0
- Autogenerated by Bloom

* Fri Apr 20 2018 Dave Feil-Seifer <dave@cse.unr.edu> - 1.6.27-0
- Autogenerated by Bloom

